#ifndef PLAYERSKILL_H
#define PLAYERSKILL_H

#define PLAYER_SKILL_SLOT_PRIMARY 0
#define PLAYER_SKILL_SLOT_SECONDARY 1
#define PLAYER_SKILL_SLOT_COUNT 2

#define MAX_TERRORIST_MINES 3

#include "main.h"

// ==========================================================
// 플레이어 스킬 설정
// ==========================================================
#define PLAYER_SKILL_STEALTH_FRAMES ((int)(5.0f * GAMEFPS))
#define PLAYER_SKILL_STEALTH_COOLDOWN_FRAMES ((int)(20.0f * GAMEFPS))

#define PLAYER_SKILL_AMMOBOOST_FRAMES ((int)(8.0f * GAMEFPS))
#define PLAYER_SKILL_AMMOBOOST_COOLDOWN_FRAMES ((int)(30.0f * GAMEFPS))

#define PLAYER_SKILL_SCAN_CHARGE_FRAMES ((int)(3.0f * GAMEFPS))
#define PLAYER_SKILL_SCAN_FRAMES ((int)(5.0f * GAMEFPS))
#define PLAYER_SKILL_SCAN_COOLDOWN_FRAMES ((int)(30.0f * GAMEFPS))

// 대장 F: 지점 지정 폭격
#define PLAYER_SKILL_ARTILLERY_STRIKE_FRAMES ((int)(7.0f * GAMEFPS))
#define PLAYER_SKILL_ARTILLERY_STRIKE_COOLDOWN_FRAMES ((int)(45.0f * GAMEFPS))
#define PLAYER_SKILL_ARTILLERY_STRIKE_AIM_DIST 400.0f
#define PLAYER_SKILL_ARTILLERY_STRIKE_RADIUS 70.0f
#define PLAYER_SKILL_ARTILLERY_STRIKE_HEIGHT 80.0f
#define PLAYER_SKILL_ARTILLERY_STRIKE_INSTALL_DELAY_FRAMES ((int)(1.5f * GAMEFPS))
#define PLAYER_SKILL_ARTILLERY_STRIKE_TICK_INTERVAL_FRAMES ((int)(0.45f * GAMEFPS))

// 현재 폭격은 직접 피해가 아니라 실제 수류탄 폭발을 사용한다.
// 이 값은 추후 직접 피해 방식으로 되돌릴 때를 대비해 남겨둔다.
#define PLAYER_SKILL_ARTILLERY_STRIKE_DAMAGE 12

// 매 틱마다 범위 안 여러 지점에 실제 수류탄 폭발을 발생시킨다.
#define PLAYER_SKILL_ARTILLERY_STRIKE_EFFECT_MIN_COUNT 3
#define PLAYER_SKILL_ARTILLERY_STRIKE_EFFECT_MAX_COUNT 5
#define PLAYER_SKILL_ARTILLERY_STRIKE_EXPLOSION_RANGE_SCALE 0.60f
#define PLAYER_SKILL_ARTILLERY_STRIKE_EXPLOSION_Y_OFFSET 14.0f
#define PLAYER_SKILL_ARTILLERY_STRIKE_EXPLOSION_SPAWN_RADIUS_RATE 0.45f

#define PLAYER_SKILL_HEAL_COOLDOWN_FRAMES ((int)(20.0f * GAMEFPS))
#define PLAYER_SKILL_HEAL_EFFECT_FRAMES ((int)(0.30f * GAMEFPS))

#define PLAYER_SKILL_IRONBODY_FRAMES ((int)(5.0f * GAMEFPS))
#define PLAYER_SKILL_IRONBODY_COOLDOWN_FRAMES ((int)(25.0f * GAMEFPS))

#define PLAYER_SKILL_SURVIVAL_FRAMES ((int)(5.0f * GAMEFPS))
#define PLAYER_SKILL_SURVIVAL_COOLDOWN_FRAMES ((int)(25.0f * GAMEFPS))
#define PLAYER_SKILL_SURVIVAL_EFFECT_FRAMES ((int)(0.30f * GAMEFPS))

// 시민B: 긴급 회피
#define PLAYER_SKILL_DODGE_COOLDOWN_FRAMES ((int)(15.0f * GAMEFPS))
#define PLAYER_SKILL_DODGE_INVINCIBLE_FRAMES ((int)(0.30f * GAMEFPS))
#define PLAYER_SKILL_DODGE_DISTANCE 40.0f

#define PLAYER_SKILL_ABSORB_FRAMES ((int)(6.0f * GAMEFPS))
#define PLAYER_SKILL_ABSORB_COOLDOWN_FRAMES ((int)(30.0f * GAMEFPS))

#define PLAYER_SKILL_MARKSHOT_FRAMES ((int)(10.0f * GAMEFPS))
#define PLAYER_SKILL_MARKSHOT_PREP_FRAMES ((int)(1.0f * GAMEFPS))
#define PLAYER_SKILL_MARKSHOT_COOLDOWN_FRAMES ((int)(30.0f * GAMEFPS))
#define PLAYER_SKILL_MARKSHOT_REFUND_FRAMES ((int)(15.0f * GAMEFPS))
#define PLAYER_SKILL_MARKSHOT_MAX_DIST 600.0f

#define PLAYER_SKILL_ROBOT_EXECUTE_FRAMES ((int)(10.0f * GAMEFPS))

// 발동 직후 2초 동안은 화면 페이드 + 마커 미표시 + 처형 불가
#define PLAYER_SKILL_ROBOT_EXECUTE_PREP_FRAMES ((int)(2.0f * GAMEFPS))

// 준비 2초 이후 실제 마커/처형 가능 시간
#define PLAYER_SKILL_ROBOT_EXECUTE_ACTIVE_FRAMES (PLAYER_SKILL_ROBOT_EXECUTE_FRAMES - PLAYER_SKILL_ROBOT_EXECUTE_PREP_FRAMES)

// 순차 처형 간격: 0.2초
#define PLAYER_SKILL_ROBOT_EXECUTE_FIRE_INTERVAL_FRAMES ((int)(0.2f * GAMEFPS))

// 취소/시간초과 쿨타임
#define PLAYER_SKILL_ROBOT_EXECUTE_CANCEL_COOLDOWN_FRAMES ((int)(20.0f * GAMEFPS))

// 좌클릭으로 실제 처형을 발동했을 때의 쿨타임
#define PLAYER_SKILL_ROBOT_EXECUTE_FIRE_COOLDOWN_FRAMES ((int)(45.0f * GAMEFPS))

#define PLAYER_SKILL_ROBOT_EXECUTE_MAX_TARGETS 10
#define PLAYER_SKILL_ROBOT_EXECUTE_MAX_DIST 500.0f
#define PLAYER_SKILL_ROBOT_EXECUTE_FOV_DEG 45.0f

// 로봇 F: 에임핵
// 1차 구현은 탄 판정 수정 없이, 조준점 근처의 적을 향해 약하게 조준 보정만 한다.
#define PLAYER_SKILL_AIMHACK_FRAMES ((int)(8.0f * GAMEFPS))
#define PLAYER_SKILL_AIMHACK_COOLDOWN_FRAMES ((int)(35.0f * GAMEFPS))

// 로봇 F: 에임핵
// 조준 보정이 확실히 체감되도록 1차 테스트에서는 강하게 잡는다.
// 너무 강하면 ASSIST_RATE / MAX_YAW_STEP / MAX_PITCH_STEP를 낮추면 된다.
#define PLAYER_SKILL_AIMHACK_MAX_DIST 900.0f

// 너무 넓으면 한번 잡은 적에게 계속 끌려가서 대상 전환이 어렵다.
// 30~40도 정도가 가장 무난하다.
#define PLAYER_SKILL_AIMHACK_FOV_DEG 70.0f

// 0.80f 이상은 화면 고정감이 강하다.
// 대상 변경이 가능하도록 0.40~0.55 사이를 추천한다.
#define PLAYER_SKILL_AIMHACK_ASSIST_RATE 0.45f

// 한 프레임에 회전 가능한 최대량도 낮춰서 강제 고정감을 줄인다.
#define PLAYER_SKILL_AIMHACK_MAX_YAW_STEP_DEG 12.0f
#define PLAYER_SKILL_AIMHACK_MAX_PITCH_STEP_DEG 8.0f

// 테러리스트 E: 교란 장치
#define PLAYER_SKILL_DISTRACTION_FRAMES ((int)(3.5f * GAMEFPS))
#define PLAYER_SKILL_DISTRACTION_COOLDOWN_FRAMES ((int)(20.0f * GAMEFPS))
#define PLAYER_SKILL_DISTRACTION_AIM_DIST 20.0f
#define PLAYER_SKILL_DISTRACTION_INSTALL_DELAY_FRAMES ((int)(1.0f * GAMEFPS))
#define PLAYER_SKILL_DISTRACTION_RADIUS 200.0f

#define PLAYER_SKILL_DISTRACTION_BEEP_INTERVAL_FRAMES ((int)(1.0f * GAMEFPS))
#define PLAYER_SKILL_DISTRACTION_BEEP_MAX_COUNT 3

// 테러리스트 F: 지뢰 설치
#define PLAYER_SKILL_TERRORIST_MINE_COOLDOWN_FRAMES ((int)(12.0f * GAMEFPS))
#define PLAYER_SKILL_TERRORIST_MINE_AIM_DIST 20.0f
#define PLAYER_SKILL_TERRORIST_MINE_INSTALL_DELAY_FRAMES ((int)(0.5f * GAMEFPS))
#define PLAYER_SKILL_TERRORIST_MINE_TRIGGER_RADIUS 7.0f
#define PLAYER_SKILL_TERRORIST_MINE_TRIGGER_HEIGHT 8.0f
#define PLAYER_SKILL_TERRORIST_MINE_EXPLODE_DELAY_FRAMES 5
#define PLAYER_SKILL_TERRORIST_MINE_ARM_DELAY_FRAMES ((int)(1.0f * GAMEFPS))
#define PLAYER_SKILL_TERRORIST_MINE_EXPLOSION_RANGE_SCALE 1.15f

#define PLAYER_SKILL_SUPPRESS_COOLDOWN_FRAMES ((int)(35.0f * GAMEFPS))
#define PLAYER_SKILL_SUPPRESS_MARK_FRAMES ((int)(3.0f * GAMEFPS))
#define PLAYER_SKILL_SUPPRESS_MAX_DIST 300.0f

// 경찰: 방패 무기
#define PLAYER_SKILL_SHIELD_MOVE_SPEED_MULT 0.80f

// 좀비: 갈고리
// OpenXOPS 좌표계 기준 300.0f 정도가 약 30m처럼 쓰이고 있으므로,
// 첫 구현은 약 26m 정도로 시작한다.
#define PLAYER_SKILL_HOOK_PREP_FRAMES ((int)(0.35f * GAMEFPS))
#define PLAYER_SKILL_HOOK_PULL_FRAMES ((int)(1.25f * GAMEFPS))
#define PLAYER_SKILL_HOOK_COOLDOWN_FRAMES ((int)(10.0f * GAMEFPS))

// 갈고리 사거리
#define PLAYER_SKILL_HOOK_MAX_DIST 260.0f

// 조준선이 적 몸통 근처를 지나가면 명중으로 인정하는 반경.
// 너무 작으면 맞히기 어렵고, 너무 크면 자동 조준처럼 느껴진다.
#define PLAYER_SKILL_HOOK_HIT_RADIUS 5.5f

// 플레이어 앞 어느 정도 거리에서 멈출지
#define PLAYER_SKILL_HOOK_STOP_DIST 18.0f

// 직접 위치 보정 속도.
// AddPosOrder()가 아니라 SetPosData()로 보정하므로 너무 크게 잡지 않는다.
#define PLAYER_SKILL_HOOK_PULL_SPEED 7.0f

// 갈고리가 붙는 높이.
// 0.50f는 몸통 중앙, 0.60f는 가슴 쪽이다.
// 다리 쪽으로 붙어 보이면 값을 올린다.
#define PLAYER_SKILL_HOOK_ATTACH_HEIGHT_RATE 0.58f

// 갈고리 표시 원통(감싸는 표시)의 중심/높이
#define PLAYER_SKILL_HOOK_WRAP_CENTER_RATE 0.58f
#define PLAYER_SKILL_HOOK_WRAP_HEIGHT_RATE 0.28f

// 플레이어 쪽 갈고리 시작 높이.
// VIEW_HEIGHT를 그대로 쓰면 화면/눈 위치에서 나가는 느낌이 강하므로,
// 몸통 앞쪽에서 나가게 약간 낮춘다.
#define PLAYER_SKILL_HOOK_PLAYER_ATTACH_HEIGHT 9.0f

// 갈고리 선이 몸 안쪽에서 시작하지 않도록 정면으로 조금 밀어낸다.
#define PLAYER_SKILL_HOOK_PLAYER_FORWARD_OFFSET 4.0f

// 좀비: 격노
#define PLAYER_SKILL_RAGE_FRAMES ((int)(6.0f * GAMEFPS))
#define PLAYER_SKILL_RAGE_COOLDOWN_FRAMES ((int)(25.0f * GAMEFPS))

// 격노 효과
#define PLAYER_SKILL_RAGE_MOVE_SPEED_MULT 1.44f
#define PLAYER_SKILL_RAGE_ATTACK_DAMAGE_MULT 1.44f
#define PLAYER_SKILL_RAGE_FIRE_WAIT_MULT 0.56f
#define PLAYER_SKILL_RAGE_DAMAGE_TAKEN_MULT 1.44f
#define PLAYER_SKILL_RAGE_LIFESTEAL_RATE 0.44f

// 동료 소환: 외형만 아군 계열 텍스쳐로 입힌다.
// 실제 능력치/AI/타입은 29, 30, 31번 좀비를 유지한다.
#define PLAYER_SKILL_SUMMON_COOLDOWN_FRAMES ((int)(25.0f * GAMEFPS))
#define PLAYER_SKILL_SUMMON_AIM_DIST 60.0f
#define PLAYER_SKILL_SUMMON_COUNT 3
#define PLAYER_SKILL_SUMMON_EFFECT_FRAMES ((int)(0.45f * GAMEFPS))
#define PLAYER_SKILL_SUMMON_INSTALL_DELAY_FRAMES ((int)(0.7f * GAMEFPS))
#define PLAYER_SKILL_SUMMON_DEAD_REMOVE_DELAY_FRAMES ((int)(2.5f * GAMEFPS))

#define PLAYER_SKILL_SUMMON_ZOMBIE_ID1 29
#define PLAYER_SKILL_SUMMON_ZOMBIE_ID2 30
#define PLAYER_SKILL_SUMMON_ZOMBIE_ID3 31


#define PLAYER_SKILL_SUMMON_ALLY_TEXTURE_COUNT 5

#define PLAYER_SKILL_SHADOW_DECOY_FRAMES ((int)(8.0f * GAMEFPS))
#define PLAYER_SKILL_SHADOW_DECOY_COOLDOWN_FRAMES ((int)(25.0f * GAMEFPS))
#define PLAYER_SKILL_SHADOW_DECOY_AIM_DIST 60.0f
#define PLAYER_SKILL_SHADOW_DECOY_INSTALL_DELAY_FRAMES ((int)(0.7f * GAMEFPS))
#define PLAYER_SKILL_SHADOW_DECOY_HP 50
#define PLAYER_SKILL_SHADOW_DECOY_PING_FRAMES ((int)(5.0f * GAMEFPS))

// 요원B F: 생체장
#define PLAYER_SKILL_BIOTIC_FIELD_FRAMES ((int)(6.0f * GAMEFPS))
#define PLAYER_SKILL_BIOTIC_FIELD_COOLDOWN_FRAMES ((int)(30.0f * GAMEFPS))
#define PLAYER_SKILL_BIOTIC_FIELD_INSTALL_DELAY_FRAMES ((int)(0.5f * GAMEFPS))
#define PLAYER_SKILL_BIOTIC_FIELD_AIM_DIST 20.0f
#define PLAYER_SKILL_BIOTIC_FIELD_RADIUS 35.0f
#define PLAYER_SKILL_BIOTIC_FIELD_HEIGHT 18.0f
#define PLAYER_SKILL_BIOTIC_FIELD_HEAL_INTERVAL_FRAMES ((int)(0.5f * GAMEFPS))
#define PLAYER_SKILL_BIOTIC_FIELD_HEAL_AMOUNT 10

#define PLAYER_SKILL_TELEPORT_COOLDOWN_FRAMES ((int)(35.0f * GAMEFPS))
#define PLAYER_SKILL_TELEPORT_CAST_FRAMES ((int)(0.5f * GAMEFPS))
#define PLAYER_SKILL_TELEPORT_EFFECT_FRAMES 16
#define PLAYER_SKILL_TELEPORT_AIM_DIST 250.0f

enum PlayerSkillGroup
{
	PLAYER_SKILL_GROUP_NONE = 0,
	PLAYER_SKILL_GROUP_SECRET_AGENT,
	PLAYER_SKILL_GROUP_SOLDIER,
	PLAYER_SKILL_GROUP_CAPTAIN,
	PLAYER_SKILL_GROUP_CIVILIAN_A,
	PLAYER_SKILL_GROUP_CIVILIAN_B,
	PLAYER_SKILL_GROUP_MERCENARY,
	PLAYER_SKILL_GROUP_AGENT_A,
	PLAYER_SKILL_GROUP_ROBOT,
	PLAYER_SKILL_GROUP_TERRORIST,
	PLAYER_SKILL_GROUP_AGENT_B,
	PLAYER_SKILL_GROUP_POLICE,
	PLAYER_SKILL_GROUP_ZOMBIE
};

enum PlayerSkillType
{
	PLAYER_SKILL_NONE = 0,
	PLAYER_SKILL_STEALTH,
	PLAYER_SKILL_AMMOBOOST,
	PLAYER_SKILL_TACTICAL_SCAN,
	PLAYER_SKILL_HEAL,
	PLAYER_SKILL_SURVIVAL,
	PLAYER_SKILL_ABSORB,
	PLAYER_SKILL_MARKSHOT,
	PLAYER_SKILL_ROBOT_EXECUTE,
	PLAYER_SKILL_DISTRACTION,
	PLAYER_SKILL_SUMMON,
	PLAYER_SKILL_SUPPRESS,
	PLAYER_SKILL_HOOK,
	PLAYER_SKILL_IRONBODY,
	PLAYER_SKILL_RAGE,
	PLAYER_SKILL_DODGE,
	PLAYER_SKILL_TELEPORT,
	PLAYER_SKILL_IMPACT_GRENADE,
	PLAYER_SKILL_SHIELD,
	PLAYER_SKILL_DP28,
	PLAYER_SKILL_TERRORIST_MINE,
	PLAYER_SKILL_BIOTIC_FIELD,
	PLAYER_SKILL_ARTILLERY_STRIKE,
	PLAYER_SKILL_SHADOW_DECOY,
	PLAYER_SKILL_AIMHACK
};

class human;

// 스킬 데이터 조회 함수
int PlayerSkill_GetGroupByHuman(human* myHuman);
int PlayerSkill_GetTypeByGroup(int group, int slot);
int PlayerSkill_GetTypeByHuman(human* myHuman);
bool PlayerSkill_HasSkill(human* myHuman);
int PlayerSkill_GetCooldownFrames(int skilltype);
int PlayerSkill_GetDurationFrames(int skilltype);
float PlayerSkill_GetTargetingMaxDist(int skilltype);
bool PlayerSkill_IsRayTargetingSkill(int skilltype);
bool PlayerSkill_IsGroundTargetingSkill(int skilltype);
bool PlayerSkill_IsTargetingSkill(int skilltype);
bool PlayerSkill_IsSimpleBuffSkill(int skilltype);
bool PlayerSkill_IsSpecialActiveSkill(int skilltype);
bool PlayerSkill_IsBlockedWhileReloading(int skilltype);
int PlayerSkill_GetIconID(int skilltype);
const char* PlayerSkill_GetFallbackIconText(int skilltype);

#endif